site_name: ToastAnalytics Guide
theme: readthedocs

docs_dir: docs
site_dir: docs
pages:
- ['index.md', 'Introduction', 'Welcome to Toast Analytics']

- ['Developer/1. Getting Started.md', 'Operator Guide', 'Getting Started']
- ['Developer/3. marketing Guide.md', 'Operator Guide', 'Marketing(Comming Soon)']

- ['Developer/4. Android Developer Guide.md', 'Developer Guide', 'Android']
- ['Developer/5. iOS Developer Guide.md', 'Developer Guide', 'iOS']
- ['Developer/6. Unity Developer Guide.md', 'Developer Guide', 'Unity']
- ['Developer/9. Error Code.md', 'Developer Guide', 'API Return Code']

